### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by sgt-kabukiman** [speedruncom/api#1]
Right now, I've skipped adding pagination to our collections, because I'm not 100% sure what approach is the best.

##### ?page=...

This one is simple: append a page number in the query string (like in ``/users?page=42``) to navigate between individual pages.

Pro:

* extremely simple, both for us and for 3rd party developers

Contra:

* not very flexible: page size is fixed
* is page 0 or 1 the first? :arrow_right: need to document and make sure people don't fuck up
* API clients need the knowledge how to navigate between the pages of collections (i.e. know to increment a page number and append that to the query string).

##### ?offset=N&limit=M

Instead of using fixed-size pages, allow clients to control the offset/limit (within reasonable limits) themselves.

Pro:

* more flexible than the first approach,
* but still relatively simple

Contra:

* again, hard-coded pagination logic in all API clients

##### (Intermission)

Both approaches are simple, but suffer from two main issues:

* We need to document and API clients need to implement the pagination logic. Generally, the less an API client needs to know, the better, so it would be nice to make this easier.
* Pagination is not *stable*. I.e. if new elements are added or removed from a collection, the paging can suddenly show seemingly duplicated elements (the last element from page N suddenly appears as the first one on page (N+1)).

##### RESTy approach

Instead of documenting how to manually browse through pages, we include next/prev links in our API responses. The links contain the information about offset, limit and possibly other stuff (see below) as an opaque token (e.g. like ``/users?cursor=Myw0MjA=``, where ``Myw0MjA=`` is base64 for ``3,420``, which could stand for 3rd page with 420 on each page). API clients then *never* construct their own URLs, but rather just follow the links we give them.

Pro:

* real RESTness
* less hardcoded knowledge in API clients
* more flexibility for us (we can change what and how we encode the cursor token at any time, because no API client needs to care about the format)
* We can easily make pagination stable. For example, we could add the current *time* when the API client requested the first page to the token (e.g. ``base64_encode("3,420,1433611708")``). This way, when fetching the next page, we can skip all newer elements and give the client one consistent view of the data.

Contra:

* can be a burden to implement for clients
* no more jumping to a specific page (unless API developers are evil and decode the token and build their own -- still, I would not go as far as to actually encrypt them)

##### Combinations

Of course, we can easily combine things, like using ``?page=...`` but still have pre-generated links to the next/prev pages in our API responses.

**Comment by sgt-kabukiman** [comment]
@CryZe, what do you think?

**Comment by CryZe** [comment]
No idea, I think the second approach is the best. That way a client can show the games for examples as individual pages where the user can just click on the 5th page or whatever and the client is then able to just query the 5th page, instead of going through the "next" links of the third approach. Also, this way the client can easily just show 10 games per page, instead of whatever your default is.

**Comment by sgt-kabukiman** [comment]
Hmm, those are some valid points against the third approach. Let's meet in the middle and go with the second option, plus links for lazy API clients.

**Comment by sgt-kabukiman** [comment]
https://github.com/speedruncom/api/blob/master/version1/pagination.md
