### ISSUE TITLE
Sorting by "popularity"?

### ISSUE THREAD

**Issue by Cronikeys** [speedruncom/api#11]
It'd be cool to get sorting by number of runs or something. There are probably other ways to measure "popularity," but sorting by # of runs would do for now

Example: querying games?name=super mario world gives Super Mario Advance 2: Super Mario World as the first result whereas with an orderby=popularity it could provide the actual smw

**Comment by CryZe** [comment]
:+1: I have the same issue

**Comment by wooferzfg1** [comment]
Sorting by "closest match" would be useful too so that you can easily query a game when you have its exact game name, since there's no way to do that at the moment without getting all of the games from the fuzzy search.
