### ISSUE TITLE
API's Faulty: API lists 1st place run as 5th place in their API......

### ISSUE THREAD

**Issue by ghost** [speedruncom/api#110]
...

**Comment by GB127** [comment]
That's not true. You need to narrow down the request by using variables.

https://www.speedrun.com/api/v1/leaderboards/v1pozgp6/level/r9gr14jw/zdnxwnx2?var-j845zj5n=4lx9vg3l

Try with this.

**Comment by GB127** [comment]
Woops, look like I got the wrong leaderboard or something. But the affirmation is the same : it can work.

**Comment by Bluely-NO-STALKING-MYSELF-ALLOWED** [comment]
> Woops, look like I got the wrong leaderboard or something. But the affirmation is the same : it can work.

oh ok, should i close the issue?
