### ISSUE TITLE
There seems to be no way of distinguishing Games and Series

### ISSUE THREAD

**Issue by CryZe** [speedruncom/api#12]
There's no indicator of whether something is a Series or a Game. You'd need to query for the Children of the game and see if there's any, but that's an additional API call. I don't think it's a good idea that you have to query the API an additional time every time you get a game from the API, cause you don't know whether it has children and is therefore a series or not.

**Comment by CryZe** [comment]
In my opinion the API should completely distinguish games and series as two different things. This might be hard to do, as the database doesn't distinguish between them either. This should be fixed in the API to at least some degree though, as every client otherwise needs to implement handling these edge cases, where you accidently deal with a series instead of the game.

**Comment by sgt-kabukiman** [comment]
One of the problems with the series/game distinction is that is f*cks you really hard in case of romhacks, which are children of _games_. So it's not really a series -> game hierarchy, but rather some fuzzy tree structure where nodes are named depending on a number of factors.

@Lighnat0r what do you think? Can we cleanly distinguish between games, series and others?

**Comment by CryZe** [comment]
Can we at least have some kind of "HasParent", "HasChildren" information? (In the bulk download too)

**Comment by sgt-kabukiman** [comment]
*Especially* in the bulk mode, this information would not be available, as it's basically one more query per game.

**Comment by CryZe** [comment]
Then bulk mode would be completely useless to me, cause I definitely don't want to show the series and I'd need to query the game list through normal means, which would cause soooo much overhead. Can I have it at least as some kind of optional embed?

**Comment by Lighnat0r** [comment]
Simply put, series have no parent (i.e. 0), games/rom hacks have a non-zero parent (even those not in a series, which are technically in the 'Other' series. It's kinda non-obvious from the site so it might be a good idea to point this out in the API documentation as well?).

Further distinguishing rom hacks from games is harder though, as the only way to really do it is an extra query to check if the parent has a parent.

An update to overhaul the series-games relation has been needed for some time and will still happen at a point in the future, but shouldn't be relied on to solve this as it might take a while.

**Comment by sgt-kabukiman** [comment]
Okay we've made the necessary changes to more easily distinguish between series, games and romhacks. We will go on to split series apart from games/romhacks and make romhacks easier to discover/distinguish from "regular games".

**Comment by CryZe** [comment]
That's good news :+1:

**Comment by sgt-kabukiman** [comment]
Series and games are now separated in the API.
