### ISSUE TITLE
Unannounced breaking change in `Variable` structure that could lead to fatal errors for API clients

### ISSUE THREAD

**Issue by exodustx0** [speedruncom/api#146]
[Example request](https://www.speedrun.com/api/v1/variables/38dwjgxn).

The `{Variable}.values.values.{id}` objects are [documented](https://github.com/speedruncomorg/api/blob/master/version1/variables.md#structure) to always have properties `label`, `rules` and `flags`. However, in the example request, we can see that only `label` is defined. Any active code that went with the implication that the `flags` property would always be defined, as the documentation suggests, would run into a fatal error when trying to access `flags.miscellaneous`.

**Comment by Nick-NCSU** [comment]
In your example request it seems that is-subcategory is false. According to the documentation you sent "For non-subcategory values, rules and flags are not defined."

**Comment by exodustx0** [comment]
Oh bobbins. I must've totally glossed over that. Deepest apologies!
