### ISSUE TITLE
Variables still respond with integer IDs

### ISSUE THREAD

**Issue by CryZe** [speedruncom/api#15]
The category fields and possibly other fields still return integer IDs which is clearly a bug.

This is one of those cases: http://www.speedrun.com/api/v1/variables/0nwkrrnq

**Comment by CryZe** [comment]
SpeedrunComSharp parses this as null for example, making it impossible to figure out the variables that are relevant for the category.

**Comment by sgt-kabukiman** [comment]
Fixed.
