### ISSUE TITLE
Emulators are not allowed according to API when they actually are

### ISSUE THREAD

**Issue by CryZe** [speedruncom/api#16]
For some reason the API returns that Emulators are not allowed, when the website actually allows it.

Here's an example of that: 

http://www.speedrun.com/smb1/editrun#Any%25
http://www.speedrun.com/api/v1/games/om1m3625

**Comment by sgt-kabukiman** [comment]
Thanks, the API incorrectly reported the ``emulator-allowed`` flag. Fixed now.
