### ISSUE TITLE
[Feature request] API Routes for `/challenges`

### ISSUE THREAD

**Issue by wRadion** [speedruncom/api#176]
Currently, as far as I know, there's no way to get the runs from a challenge or anything really. It would be cool to have a `/challenges/:id` that basically act like `/games/:id` so you can get all the runs, leaderboards, etc...

**Comment by ManicJamie** [comment]
This API is no longer actively maintained; see [APIv2](https://github.com/ManicJamie/speedruncom-apiv2-docs).

For your purposes, see `/api/v2/GetChallengeLeaderboard`.

**Comment by wRadion** [comment]
Aaaaah oh what, I didn't even know about this, thanks!
