### ISSUE TITLE
Query API URL through HTTP Header of Site URL

### ISSUE THREAD

**Issue by CryZe** [speedruncom/api#18]
Instead of parsing the HTML, you should be able to get the API URL through the HTTP Header of the response of querying the Site URL. You could remove the "Access as JSON" fields from the website then too, as it's mostly useless for 99% of the users.

**Comment by sgt-kabukiman** [comment]
The "Access as JSON" link is meant to promote the API, so at the moment, that link will not go anywhere. But having the link as a HTTP header *as well* is a good idea.

**Comment by sgt-kabukiman** [comment]
Okay, that "moment" was a really short moment.

As the links to the API are now present in the form of [RFC 5988](https://tools.ietf.org/html/rfc5988)-compatible Link headers, I removed the links from the markup. People complained they don't understand it, they're scared of everything but GIFs and kittens on the interwebs and I don't want to constantly justify living in the 21st century. There, the naysayers win.

Links take the form of

    Link: </api/v1/runs/pzgvw1vz>; rel="alternate http://www.speedrun.com/api"

At the moment, only the URI changes, the relation is the same for all API links. Also, at the moment, there is only one Link header that also only contains one link. That could change at some point, but for that we'd need better relations to make parsing the header easier.
