### ISSUE TITLE
Records API returns the wrong places

### ISSUE THREAD

**Issue by CryZe** [speedruncom/api#19]
The Places are not correct when there's a tie, like in the _meme game_ [Barney's Hide & Seek Game](http://www.speedrun.com/Barneys_Hide_and_Seek_Game). The Records API returns the places in ascending order instead of putting them all on the first place.

[Here](http://www.speedrun.com/api_records.php?game=Barney's Hide %26 Seek Game&amount=99999)

**Comment by sgt-kabukiman** [comment]
This repository is not about the old API, but I'll keep this ticket as a reminder for us.

**Comment by CryZe** [comment]
Well, not really needed to be fixed anymore.
