### ISSUE TITLE
Getting a Game List is too slow

### ISSUE THREAD

**Issue by CryZe** [speedruncom/api#2]
Getting a list of all the games, which we definitely want in LiveSplit, is just way too slow. It takes like 30 seconds or something till everything is downloaded and parsed. That's basically unusable. It would be cool if you guys could add a lightweight game list that simply contains the game names and their IDs, but all games. This way the response is pretty small, you can query all games and if you are interested in more, you can query the game you are interested in itself.

**Comment by sgt-kabukiman** [comment]
The issue is not in the API itself, but the server, which is pretty slow at the moment (but out of my control, unfortunately).

I will see what we can do to make bulk requests easier in general.

**Comment by CryZe** [comment]
So far we've been parsing http://www.speedrun.com/games which is pretty much instant. So something similar to this (just in JSON) would be good.

**Comment by glacials** [comment]
Getting a list of all games, whether it's just names/ids or everything, doesn't sound like it would scale well in the future. Even if your server is very beefy and can return 1,000,000 JSON games in 1 second, the client still has to store all that JSON in memory, parse it, and store the results in memory.

The long-term answer is probably either a search-type mechanism, or pagination for the global games list.

**Comment by sgt-kabukiman** [comment]
Yes and once you have an established TCP connection, even the API responds quickly.

I can't make a simple ``SELECT * FROM games WHERE 1 ORDER BY id`` much faster. Again, it's the server that has issues at the moment.

What I'm currently tinkering with is adding a ``?_bulk=yes`` mode to the API (or at least a few resources), which would increase the allowed number of elements per page to sth like 500 or 1k, but forbid embeds and remove the embedded links in the response. No idea if I want to also strip out certain fields and basically maintain two possible representations per resource (one normal, one bulk).

**Comment by CryZe** [comment]
> I can't make a simple SELECT * FROM games WHERE 1 ORDER BY id much faster. Again, it's the server that has issues at the moment.
Why does the website respond instantly then? It's not really a server issue, the server can handle ~3000 games. The issue is the amount of unnecessary data I need to request atm.

> doesn't sound like it would scale well in the future.
I don't think there'll every be way more than 10000 games. So let's assume 10000 games * roughly 20 bytes of data (for game name, JSON overhead and id), which would roughly equal 200 KiB. That's really not a lot of data and it's actually less than a third of that atm. And I'm only querying it a single time (at the startup), so it shouldn't be any problem in any case whatsoever.

**Comment by sgt-kabukiman** [comment]
% time curl -q http://www.speedrun.com/api/v1/games > /dev/null 2> /dev/null
    0.01s user 0.00s system 0% cpu 0.573 total
    
    % time curl -q http://www.speedrun.com/api/v1/games > /dev/null 2> /dev/null
    0.00s user 0.01s system 1% cpu 0.447 total
    
    % time curl -q http://www.speedrun.com/games > /dev/null 2> /dev/null
    0.01s user 0.00s system 0% cpu 1.735 total
    
    % time curl -q http://www.speedrun.com/games > /dev/null 2> /dev/null
    0.01s user 0.02s system 1% cpu 2.000 total

The server is allowed to let 150 connections in and at the moment there are 200+, so loading times are luck dependent. So can we please drop this distracting loading time issue?

**Comment by sgt-kabukiman** [comment]
I've added the ``_bulk`` mode to the games list. You can now do http://www.speedrun.com/api/v1/games?_bulk=yes&max=1000 with 1k being the maximum. And for the record, this responds in 0.6s to me.

**Comment by CryZe** [comment]
Thanks, this works perfectly :)
