### ISSUE TITLE
Searching a Game for its Name doesn't always sort by likeness

### ISSUE THREAD

**Issue by CryZe** [speedruncom/api#24]
This is a really weird case, but for some reason the API yields different results based on how many items you choose per page. For example:

When searching for the game called ":The Game:", you expect to get it as the first result as this is the exact matching name in the speedrun.com database. For some reason it's not the first result when not limitting the amount of results per page:
http://www.speedrun.com/api/v1/games?name=%3AThe%20Game%3A

When you limit it to 1 element per page, it finds it as the first result though:
http://www.speedrun.com/api/v1/games?name=%3AThe%20Game%3A&max=1

This is not really a problem that is causing bugs for me as I always use &max=1 when searching for a game anyway, but it's definitely a bug that should be looked into.

**Comment by sgt-kabukiman** [comment]
I fucked up. Give me a second to fix that.

**Comment by sgt-kabukiman** [comment]
Fixed.
