### ISSUE TITLE
Retrieving platform titles for Wild Arms (60+ listed) causes timeout

### ISSUE THREAD

**Issue by mylogon341** [speedruncom/api#26]
After receiving array of platform IDs from a game with a lot of platforms, retrieving titles of those consoles causes time out as requests per minute is limited to 50.
I'm retrieving the platform names with a for loop, which is ok for games with a smaller number of platforms, but games like this eat up the allowance.
Is there a way to just retrieve platforms by their names or are we to deal with platform IDs?

**Comment by Lighnat0r** [comment]
You can request to embed the platform information when querying for a game. (see https://github.com/speedruncom/api/blob/master/version1/games.md#embeds)
This way you only need to do one request to get information for all platforms.

For example:
http://www.speedrun.com/api/v1/games?name=Wild%20Arms&embed=platforms

On a side note, I'm pretty sure this game isn't actually supposed to have all platforms enabled.

**Comment by mylogon341** [comment]
Thanks, I knew I was missing a trick.
I figured there was something not right about the platform list for this. That was supposed to be the other point I raised..
Thanks a lot.
