### ISSUE TITLE
_bulk=yes doesn't work on /users

### ISSUE THREAD

**Issue by mylogon341** [speedruncom/api#27]
When trying to load a list of users I added 
?_bulk=yes&max=1000
But it still responds with only 200 users. 
Is this deliberate?

**Comment by Lighnat0r** [comment]
I'm pretty sure the documentation only states that bulk mode is available for games and series which is accurate.
What is it you need bulk mode on users for exactly?

**Comment by mylogon341** [comment]
Ah. I was wondering if I was just missing it or if it'd been missed off. 
I was hoping to be able to retrieve all users before searching for them as so the list updates as the user types. Not quite sure how to do this without users being cached. Are searches possible with incomplete usernames?
Thanks

**Comment by Lighnat0r** [comment]
The name parameter does a fuzzy search, so yeah, eg:
http://www.speedrun.com/api/v1/users?name=lo
http://www.speedrun.com/api/v1/users?name=log
http://www.speedrun.com/api/v1/users?name=logo
http://www.speedrun.com/api/v1/users?name=logon

The [other parameters](https://github.com/speedruncom/api/blob/master/version1/users.md#get-users) only do exact searches, though.

**Comment by mylogon341** [comment]
This is perfect. Thanks a lot.
Luke
