### ISSUE TITLE
Why are some "players" listed as guests in records?

### ISSUE THREAD

**Issue by illuminati7** [speedruncom/api#28]
For example in the 0 Star category for Super Mario 64

http://www.speedrun.com/api/v1/categories/xk9gg6d0/records

The WR is held by アキラ (Akira)

"players":[{"rel":"guest","name":"\u30a2\u30ad\u30e9 (Akira)"

2nd place is by Xiah

"players":[{"rel":"user","id":"o866w58z"

Why does Akira show up as a guest without an account ID, but a name instead? Are these records pulled from elsewhere, and is it for Super Mario 64 only? I'd like to be able to automatically get the WR of all games (with runner name) without exceptions if possible.

**Comment by zoton2** [comment]
Guests are runners who don't have an account linked to them on the run and their name has just been input by whatever mod submitted their run. You can see that their names are not links [on the leaderboard.](http://www.speedrun.com/sm64#0_Star).

When checking the information, just check the "rel" to see if they are a guest or not. If they are, take the "name" field and if not you can take the "id" field and use that to find the user's information from the API.

[Also there's a whole page in the documentation about guests.](https://github.com/speedruncom/api/blob/master/version1/guests.md)

**Comment by sgt-kabukiman** [comment]
zoton2 explained that perfectly. Thanks :)

**Comment by lfiore** [comment]
Yes, thank you zoton.

**Comment by illuminati7** [comment]
Yes, thank you Zoton. And thanks for the API everyone.
