### ISSUE TITLE
Pagination has next link with empty page

### ISSUE THREAD

**Issue by CryZe** [speedruncom/api#3]
I'm not sure if this is intended, but the pagination can sometimes return a next link that returns a result with 0 elements. That causes unnecessary requests and should probably be fixed.
This is in a example of such a request: http://www.speedrun.com/api/v1/games?name=Zelda
Zelda has exactly 20 games, but still returns a next link.

**Comment by sgt-kabukiman** [comment]
Yes, this can happen and is a side-effect of us not wanting to count all elements in a collection, because ``COUNT(*)`` is pretty slow in InnoDB.

So this is intended behaviour and at the moment, I don't think we will change that.
