### ISSUE TITLE
Runs with NoLoads time w/o RealTime fall under RealTime for API

### ISSUE THREAD

**Issue by ROMaster2** [speedruncom/api#32]
Case in point:
https://www.speedrun.com/run/7yl727rm
https://www.speedrun.com/api/v1/runs/7yl727rm

If a run has a 'Time without loads' record and no 'Time with loads' record, the former falls into the latter becoming blatantly incorrect.

**Comment by ROMaster2** [comment]
https://www.speedrun.com/mgsv/individual_levels
MGSV is sorted by 'Time without loads', yet a lot of runs don't have that. If a run has 'Time without loads' and in-game time, it'll use the latter, but if it has 'Time with loads' instead, it'll use in-game time instead. Since the times fall into 'Time with loads' when either is absent, it's not possible to verify time without relying on the provided primary time. Failure on integrity.

**Comment by Lighnat0r** [comment]
The times structure will be overhauled for v2 and the accompanying backend changes will fix this in v1 as well.
