### ISSUE TITLE
The `platform` filter on the `runs` endpoint doesn't work

### ISSUE THREAD

**Issue by adsr** [speedruncom/api#36]
For example, I'd expect http://www.speedrun.com/api/v1/runs?platform=rdjq4vwe to return only NES runs, but it appears to be returning N64 runs at the moment:

```
$ curl -s 'http://www.speedrun.com/api/v1/runs?platform=rdjq4vwe' | jq '.data | .[] | .system.platform' | head -n5
"ow31ev96"
"ow31ev96"
"ow31ev96"
"ow31ev96"
"ow31ev96"
```

**Comment by Lighnat0r** [comment]
Closing as this has been fixed.
