### ISSUE TITLE
Why always give out the internal IDs instead of real names?

### ISSUE THREAD

**Issue by Deamon-Kid** [speedruncom/api#39]
Hello,

while trying to access this API, numerous times I found myself asking, why I always get internal IDs instead of names.
For example, getting the Personal Bests of S. (as linked in the Readme.md):
http://www.speedrun.com/api/v1/users/wzx766j7/personal-bests
While I can see most of the relevant information for a 1 Person Leaderboard quite well, there is no way to actually link the runs to a real game name. The only option I have is to take every game-id and fire up at least one seperate request to get entire entire game-objects just to find out the name.
I had the same issue when trying to get all WRs on a game, where once again, getting the times was "easy", getting the accompanied user is the hard part.

I can somewhat understand the issue on the WR-request, since users can have different names for different languages but it still increases the amount of requests per actual request by at least 100% (if a user only has records for 1 game / only one user has WRs for a game)

All of this seems like it could be solved by simply giving out some names as well as the ids with the initial request objects. I feel like linking a run to a user should be a usecase that is often needed, though I have no data besides my own needs to back this up.

I hope I could make myself clear. If there is anything unclear about my request, please let me know.

Thanks again for providing this API and thank you in advance for any response.

PS. If I am just missing a parameter / option, I am sorry for bringing this up. As it stands I couldn't find a way to recude the amount of requests.

**Comment by mylogon341** [comment]
Hey. Try this. This should embed the information that you're after.
http://www.speedrun.com/api/v1/users/wzx766j7/personal-bests?embed=game

Read up a bit more about the use of the embed parameter here:
https://github.com/speedruncom/api/blob/master/version1/users.md#get-usersidpersonal-bests
This can be used in a number of places.
Hope this helps.
Luke

**Comment by mylogon341** [comment]
ps. Also, to answer your question about 'Why'.
This is how databases work. You store the foreign key of the related data from another table. This lookup retrieves the object from the database, which will include the foreign key. This does not automatically include the data from the related table.
When you include the embed parameter, this is similar to the (afaicr) 'inner join' SQL statement.

**Comment by Deamon-Kid** [comment]
Hello Luke, 

that parameter is exactly what I was missing. Thank you very much.
I swear I read through that documentation mutliple times but it must have always slipped out of my view.

As to your explanation, I understand why an id is a useful thing. It was just that, without the aformentioned parameter, I felt that just giving away the id was "not enough".

Thanks again.
