### ISSUE TITLE
Are IDs unique across resources?

### ISSUE THREAD

**Issue by stefansundin** [speedruncom/api#41]
Hi. I just wanted to ask a quick question that I didn't see discussed anywhere.

Are IDs always unique? Or is there a possibility that a run id might be the same as a level id, for example?

I am currently caching some information from the API, and I store it in a hash like this:

```ruby
cache = {
  "levels" => {
    "rdq006ow" => "Cool, Cool Mountain"
  },
  "categories" => {
    "q254q58d" => "Single Stars"
  }
}
```

Would it be safe for me to instead store it like this?

```ruby
cache = {
  "rdq006ow" => "Cool, Cool Mountain",
  "q254q58d" => "Single Stars"
}
```

Because when I'm looking things up, I already know if it's a category or a level, so I could simplify my caching.

Thank you!

**Comment by ROMaster2** [comment]
From checking my database from a few months ago, I believe they are always unique.

**Comment by Lighnat0r** [comment]
The chance of collisions is pretty small, but they can occur between different types of resources.
