### ISSUE TITLE
Documentation missing for some Links

### ISSUE THREAD

**Issue by CryZe** [speedruncom/api#6]
I don't see Splits I/O links in the documentation for the runs, so I guess they are missing.

**Comment by sgt-kabukiman** [comment]
splits.io links are included along the other links, see http://www.speedrun.com/api/v1/runs/225

**Comment by CryZe** [comment]
The documentation should mention that in my opinion. This can easily be missed.

**Comment by sgt-kabukiman** [comment]
Only API-relevant links are now placed within ``links``, all others are dedicated and documented fields in the representations of users, runs etc.
