### ISSUE TITLE
500 error for runs

### ISSUE THREAD

**Issue by shauninman** [speedruncom/api#61]
About 12 hours ago the API started returning a 500 error for requests like the following:

`https://www.speedrun.com/api/v1/runs/mk4o855y?embed=players,category,game,platform`

It appears to be caused by the `players` embed as the following request works:

`https://www.speedrun.com/api/v1/runs/mk4o855y?embed=category,game,platform`

**Comment by retroph** [comment]
I noticed the same issue yesterday.

Seems to be working correctly again now.

**Comment by pac-** [comment]
Fixed!
