### ISSUE TITLE
There's no way of figuring out the Place of a Run

### ISSUE THREAD

**Issue by CryZe** [speedruncom/api#8]
This API doesn't include the Records API yet, but the Runs themselves should at least include the Place of the Run. I'd implement the Records returned by the old Records API as a Subset of a Run, but due to the Place missing, they are more than just a subset at this point.

**Comment by sgt-kabukiman** [comment]
The place a run has is dependent on the run filter, i.e. the category, level, variables etc.

For example, you could be 1st place in OoT when using the "PAL-only" leaderboard but be on 32nd place when taking all regions into account.

As mentioned in the docs, ``/runs`` is **not** meant to be used as the basis for a leaderboard. This would require an API client to know and understand all the small details about how we select, group and sort runs, which is just ridiculous. ``/runs`` is meant for "data mining" tasks like "give me all rejected runs of a certain game".

Place information will be available in ``/leaderboards``.
